### PR TITLE
[EMSCRIPTEN] Add emscripten compatibility patches

### PR DESCRIPTION
**Pull request by podsvirov**
Upstream original [patches](https://github.com/emscripten-ports/asio/commit/39361397166855b614de04034d855c0321473f94).

### CODE REVIEW

**Comment by podsvirov** [comment]
Hello @cynecx, please review this PR. May be you have some remarks?

**Comment by cynecx** [comment]
I am not able to test this, nor I am up-to-data enough with the code, so I am not certain. However, this looks good to me.

**Comment by podsvirov** [comment]
With this changes I can send and reseive messages to/from WebSocket servers from my web browser.

**Comment by podsvirov** [comment]
Hello @chriskohlhoff, the project source code already has [some changes](https://github.com/chriskohlhoff/asio/search?q=emscripten&unscoped_q=emscripten) to support the [Emscripten](https://emscripten.org/) platform, can you apply this PR too?

**Comment by chriskohlhoff** [comment]
Addressed in asio version 1.16.1.

**Comment by podsvirov** [comment]
Good, thanks!

**Pull request closed without merging**
